"""add server defaults

Revision ID: 02402d844348
Revises: 8dbcf3e5f1eb
Create Date: 2025-09-27 22:07:56.651904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02402d844348'
down_revision: Union[str, Sequence[str], None] = '8dbcf3e5f1eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loans', 'status',
               existing_type=sa.VARCHAR(),
               server_default='PENDING',
               existing_nullable=False)
    op.alter_column('loans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('loans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('loans', 'reason',
               existing_type=sa.VARCHAR(),
               server_default='Pending review',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loans', 'reason',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('loans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('loans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('loans', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
