"""add cascade and timestamps

Revision ID: 8dbcf3e5f1eb
Revises: 4c02959218fc
Create Date: 2025-09-24 10:42:26.264914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dbcf3e5f1eb'
down_revision: Union[str, Sequence[str], None] = '4c02959218fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('loans_user_id_fkey'), 'loans', type_='foreignkey')
    op.create_foreign_key(None, 'loans', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.create_foreign_key(op.f('loans_user_id_fkey'), 'loans', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
